### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by alexandermorales-dev**
Added columns 1,2,3

Implemented bootstrap classes and relied mostly on them for responsiveness.

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
Hey guys, I can see you have worked hard so far, and your project is as good as the original💪
There are few issues that have prevented you from moving forward, let's address them before we move

make sure that all images have a link(clickable).
all titles have a heading and a link(clickable).
Please check all screenshots and make changes in all screen sizes.
clone-free signup
original-free-signup

Please remove the margin on the desktop, check the original.
original-full


Fix the more stories part, the image and content are supposed to be side by side, check screenshot.
more stories
original-more stories


Fix my turn on a mobile screen, see screenshot
my-turn
original-my-turn

Note: free signup area should be worked on in all screen sizes, it does not look like the original.
Please include one missing part in column 2, (culture & travel).

When you make all the changes, submit another review.
Remember "As described in the Code reviews limit Policy you have 2 code reviews left for this project."
In case you have any questions concerning the review, please reach me on slack, elisha kyakopo
Happy coding🎉✔👈💪

**Comment by elisha2kyakpo1** [comment]
Sorry I commented on the last milstone

**Comment by DanSam5K** [comment]
> Sorry I commented on the last milstone

Alright, Sir Noted we will implement the bug you spotted from the review. 
Thank you for your quick response. 💪

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @AlexJustAlex2020 @DanSam5K, good job on your clone! 🔥 

You worked hard in all the instructions that the previous Code Reviewer give you👍🏽 

Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

**Pull request merged**
